/* 
?& is a symbol I used to indicate taking a variable to 2 decimal places.
v["symbol"] is automatically generated. If you have any errors, ensure your symbol is correct!
All equation info is taken from this list
*/

let equationList = [
  {
    id: "pk_KOCR_q3_scplot",
    title: "Concentration-Response Curve",
    instructions: `Consider the following three scenarios: 
    1. Drug X interacts with Drug Y. This interaction decreases the potency of Drug Y. Click Continue to move
to the next question.
    2. Drug Y blocks a receptor. As a compensatory mechanism, the body synthesizes new receptors which raises the theoretical E<sub>MAX</sub> of the drug. 
    3. Drug W is currently given to a patient. Due to side effects, Drug W is discontinued
and Drug Z is started. Drug 2 has a lower γ.`,
    variables: [
      {
        name: "E<sub>MAX</sub>",
        units: "mg/L",
        symbol: "emax",
        min: 1,
        max: 100,
        value: 51,
        step: 1,
      },
      {
        name: "EC<sub>50</sub>",
        units: "mg/L",
        symbol: "ec50",
        min: 2,
        max: 20,
        value: 12,
        step: 1,
      },
      {
        name: "Hill's Coefficient/γ",
        units: "unitless",
        symbol: "N",
        min: 1,
        max: 10,
        value: 6,
        step: 1,
      },
    ],
    equation: '`(v["emax"]*x**v["N"])/(v["ec50"]+x^v["N"])`',
    equationTemplate: "`Effect = `",
    axis: ["concentration (mg/L)", "effect"],
    multiple_dose: false,
    x: "C",
    range: 10,
  },
  {
    id: "pk_KOCR_q2_scplot",
    title: "Concentration-Response Curve",
    instructions: `Consider the following three scenarios: 
    1. Drug X interacts with Drug Y. This interaction decreases the potency of Drug Y. Click Continue to move
to the next question.
    2. Drug Y blocks a receptor. As a compensatory mechanism, the body synthesizes new receptors which raises the theoretical E<sub>MAX</sub> of the drug. 
    3. Drug W is currently given to a patient. Due to side effects, Drug W is discontinued
and Drug Z is started. Drug 2 has a lower γ.`,
    variables: [
      {
        name: "E<sub>MAX</sub>",
        units: "mg/L",
        symbol: "emax",
        min: 1,
        max: 100,
        value: 51,
        step: 0.2,
      },
      {
        name: "EC<sub>50</sub>",
        units: "mg/L",
        symbol: "ec50",
        min: 2,
        max: 20,
        value: 12,
        step: 0.2,
      },
      {
        name: "Hill's Coefficient/γ",
        units: "unitless",
        symbol: "N",
        min: 1,
        max: 10,
        value: 6,
        step: 0.2,
      },
    ],
    equation: '`(v["emax"]*x^v["N"])/(v["ec50"]+x^v["N"])`',
    equationTemplate: "`Effect = `",
    axis: ["concentration (mg/L)", "effect"],
    multiple_dose: false,
    x: "C",
    range: 10,
  },
  {
    id: "pk_KOCR_q1_scplot",
    title: "Concentration-Response Curve",
    instructions: `Consider the following three scenarios: 
    1. Drug X interacts with Drug Y. This interaction decreases the potency of Drug Y. Click Continue to move
to the next question.
    2. Drug Y blocks a receptor. As a compensatory mechanism, the body synthesizes new receptors which raises the theoretical E<sub>MAX</sub> of the drug. 
    3. Drug W is currently given to a patient. Due to side effects, Drug W is discontinued
and Drug Z is started. Drug 2 has a lower γ.`,
    variables: [
      {
        name: "E<sub>MAX</sub>",
        units: "mg/L",
        symbol: "emax",
        min: 1,
        max: 100,
        value: 51,
        step: 0.2,
      },
      {
        name: "EC<sub>50</sub>",
        units: "mg/L",
        symbol: "ec50",
        min: 2,
        max: 20,
        value: 12,
        step: 0.2,
      },
      {
        name: "Hill's Coefficient/γ",
        units: "unitless",
        symbol: "N",
        min: 1,
        max: 10,
        value: 6,
        step: 0.2,
      },
    ],
    equation: '`(v["emax"]*x^v["N"])/(v["ec50"]+x^v["N"])`',
    equationTemplate: "`Effect = `",
    axis: ["concentration (mg/L)", "effect"],
    multiple_dose: false,
    x: "C",
    range: 10,
  },
  {
    id: "pk_mdcr_q1_scplot",
    title: "Continuous Infusion",
    instructions: `Use the slider bars to explore the impact of changes in systemic clearance (CI) and
apparent volume of distribution (V) on the concentration-time profile. Pay attention
to the time it takes to reach steady-state and the steady-state concentration. The equation being use is <math xmlns="http://www.w3.org/1998/Math/MathML"><mi>C</mi><mo>=</mo><mfrac><msub><mi>k</mi><mn>0</mn></msub><mrow><mi>C</mi><mi>l</mi></mrow></mfrac><mo>(</mo><mn>1</mn><mo>-</mo><msup><mi>e</mi><mrow><mo>-</mo><mfrac><mrow><mi>C</mi><mi>l</mi></mrow><mi>V</mi></mfrac><mo>*</mo><mi>t</mi></mrow></msup></math>`,
    variables: [
      {
        name: "Dose",
        units: "mg",
        symbol: "k_0",
        min: 250,
        max: 1000,
        value: 500,
      },
      {
        name: "Clearance",
        units: "mL/min",
        symbol: "Cl",
        min: 5,
        max: 100,
        value: 55,
      },
      {
        name: "Volume of Distribution",
        units: "L",
        symbol: "V_D",
        min: 10,
        max: 500,
        value: 250,
      },
    ],
    equation: '`(v["k_0"]/v["Cl"])*(1-2.71^(-(v["Cl"]/v["V_D"])*x))`',
    equationTemplate: "`C = `",
    axis: ["time (min)", "drug X(mg/L)"],
    multiple_dose: false,
  },
  {
    id: "pk_akct_q1_scplot",
    title: "Extravascular Administration",
    instructions: `Move the slider bar to see the effects of clearance on the concentration-time profile. Concentration is related to time using the equation <math xmlns="http://www.w3.org/1998/Math/MathML"><mtext>C=</mtext><mfrac><mrow><msub><mtext>k</mtext><mtext>a</mtext></msub><msub><mtext>*X</mtext><mtext>0</mtext></msub><mtext>&#xA0;&#xA0;</mtext></mrow><mrow><mtext>V</mtext><mfenced separators="|"><mrow><msub><mtext>k</mtext><mtext>a</mtext></msub><mtext>-k</mtext></mrow></mfenced></mrow></mfrac><mtext>*</mtext><mfenced separators="|"><mrow><msup><mtext>e</mtext><mtext>-kt</mtext></msup><msup><mtext>-e</mtext><mrow><msub><mtext>-k</mtext><mtext>a</mtext></msub><mtext>*t</mtext></mrow></msup></mrow></mfenced></math>`,
    variables: [
      {
        name: "Dose",
        units: "mg",
        symbol: "X_0",
        min: 250,
        max: 1000,
        value: 500,
      },
      {
        name: "Clearance",
        units: "mL/min",
        symbol: "Cl",
        min: 5,
        max: 50,
        value: 25,
      },
      {
        name: "Volume of Distribution",
        units: "L",
        symbol: "V_D",
        min: 50,
        max: 500,
        value: 250,
      },
      {
        name: "k<sub>a</sub>",
        units: "1/h",
        symbol: "k_a",
        min: 0.5,
        max: 5,
        value: 2.5,
      },
    ],
    equation:
      '`(v["k_a"]*v["X_0"])/(v["V_D"]*v["k_a"]-(0.06*v["Cl"]/v["V_D"]))*(2.71^(-(0.06*v["Cl"]/v["V_D"])*x)-2.71^(-v["k_a"]*x))`',
    equationTemplate: "`C = `",
    axis: ["time (min)", "drug X(mg/L)"],
    multiple_dose: false,
  },
  {
    id: "pk_ocsc_plot_pkOCSC",
    title: "CMax vs Dosing Interval",
    instructions:
      "Move the slider bar to see the effects of clearance on the concentration-time profile. Concentration is related to time using the equation C<sub>t</sub> = C<sub>0</sub>*e<sup>-K*t</sup>",
    variables: [
      {
        name: "Dose",
        units: "mg",
        symbol: "X_0",
        min: 0,
        max: 4500,
        value: 500,
      },
      {
        name: "Clearance",
        units: "mL/min",
        symbol: "Cl",
        min: 1,
        max: 35,
        value: 5,
      },
      {
        name: "Volume of Distribution",
        units: "L",
        symbol: "V_D",
        min: 0,
        max: 200,
        value: 70,
      },
    ],
    equation: '`(v["X_0"]/v["V_D"])*2.71^((-v["Cl"]/v["V_D"])*x)`',
    equationTemplate: "C = ",
    axis: ["time (min)", "drug X(mg/L)"],
    multiple_dose: false,
  },
  {
    id: "pk_mdmd_q1_mdplot",
    title: "Multiple Dosing Regimen Plot",
    instructions: `Drug X has a therapeutic range of 100 ug/L and 25 ug/L. The population average parameters for Cl and V are 25 L/h and 250 L, respectively. Targeting an average steady-state concentrations in the middle of the therapeutic range, use the sliders and buttons below to design a dosing regimen (dose and dosing interval) for IV bolus administration. <math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>C</mi><mi>t</mi></msub><mo>=</mo><mfrac><msub><mi>X</mi><mn>0</mn></msub><mi>V</mi></mfrac><mi>*</mi><mfenced separators="|"><mfrac><mrow><mn>1</mn><mo>-</mo><msup><mi>e</mi><mrow><mo>-</mo><mi>n</mi><mi>*</mi><mi>K</mi><mi>*</mi><mi>t</mi><mi>a</mi><mi>u</mi></mrow></msup></mrow><mrow><mn>1</mn><mo>-</mo><msup><mi>e</mi><mrow><mo>-</mo><mi>K</mi><mo>*</mo><mi>t</mi><mi>a</mi><mi>u</mi></mrow></msup></mrow></mfrac></mfenced><mi>*</mi><msup><mi>e</mi><mrow><mo>-</mo><mi>K</mi><mi>*</mi><mi>t</mi><mi>a</mi><mi>u</mi></mrow></msup></math>`,
    variables: [
      {
        name: "Dose",
        units: "mg",
        symbol: "X_0",
        min: 50,
        max: 4500,
        value: 1000,
        step: 1,
      },
      {
        name: "Number of Doses",
        units: "#",
        symbol: "n",
        min: 1,
        max: 40,
        value: 20,
        step: 1,
      },
      {
        name: "Volume of Distribution",
        units: "L",
        symbol: "V_D",
        min: 50,
        max: 500,
        value: 250,
        step: 1,
      },
      {
        name: "Clearance",
        units: "mL/min",
        symbol: "Cl",
        min: 1,
        max: 200,
        value: 100,
        step: 1,
      },
      {
        name: "Dosing Interval",
        units: "hr",
        symbol: "tau",
        min: 1,
        max: 7,
        value: 4,
        step: 1,
      },
    ],
    equation:
      '`(v["X_0"]/v["V_D"])*(1-2.71^(-n*0.06*(v["Cl"]/v["V_D"])*v["tau"]))/(1-2.71^(-0.06*(v["Cl"]/v["V_D"])*v["tau"]))*(2.71^(-0.06*(v["Cl"]/v["V_D"])*x))`',
    //prettier-ignore
    equationTemplate: ``,
    multiple_dose: true,
    axis: ["time", "concentration"],
  },
  {
    id: "pk_mdmp_q2_mdplot",
    title: "Multiple Dosing Regimen Plot",
    instructions: `Drug X is an antibiotic with a therapeutic range between 20 and 40 mg/L. It is administered as an IV bolus. The population average for clearance and volume are 6 L/h and 85 L, respectively. Using the slider bars, explore how changes in dose and dosing interval impact achieving concentrations within the therapeutic window while maintaining an average steady-state concentration of 30 mg/L.`,
    variables: [
      {
        name: "Dose",
        units: "mg",
        symbol: "X_0",
        min: 500,
        max: 4500,
        value: 1000,
        step: 1,
      },
      {
        name: "Number of Doses",
        units: "#",
        symbol: "n",
        min: 4,
        max: 24,
        value: 4,
        step: 2,
      },
      {
        name: "Volume of Distribution",
        units: "L",
        symbol: "V_D",
        min: 50,
        max: 500,
        value: 250,
        step: 1,
      },
      {
        name: "Clearance",
        units: "mL/min",
        symbol: "Cl",
        min: 5,
        max: 50,
        value: 100,
        step: 1,
      },
      {
        name: "Dosing Interval",
        units: "hr",
        symbol: "tau",
        min: 1,
        max: 7,
        value: 4,
        step: 1,
      },
    ],
    equation:
      '`(v["X_0"]/v["V_D"])*(1-2.71^(-n*0.06*(v["Cl"]/v["V_D"])*v["tau"]))/(1-2.71^(-0.06*(v["Cl"]/v["V_D"])*v["tau"]))*(2.71^(-0.06*(v["Cl"]/v["V_D"])*x))`',
    equationTemplate: ``,
    multiple_dose: true,
    bottomBound: 20,
    topBound: 40,
    axis: ["time (hr)", "concentration (ug/L)"],
  },
  {
    id: "dumond_pk_nonlinear-bateman",
    title: "Multiple Dosing Regimen Plot",
    instructions: ``,
    variables: [
      {
        name: "First order absorption rate constant",
        units: "hr^-1",
        symbol: "k_a",
        min: 0.1,
        max: 10,
        value: 1,
        step: 0.1,
      },
      {
        name: "Elimination rate constant",
        units: "hr^-1",
        symbol: "K",
        min: 0.01,
        max: 5,
        value: 2,
        step: 0.01,
      },
      {
        name: "Bioavailability",
        units: "",
        symbol: "F",
        min: 0,
        max: 1,
        value: 0.5,
        step: 0.02,
      },
      {
        name: "Volume of Distribution",
        units: "L",
        symbol: "V_D",
        min: 5,
        max: 5000,
        value: 500,
        step: 5,
      },
      {
        name: "Dose",
        units: "mg",
        symbol: "X_0",
        min: 1,
        max: 2000,
        value: 500,
        step: 1,
      },
    ],
    equation:
      '`(v["k_a"] * v["F"] * v["X_0"])/(v["V_D"]*(v["k_a"]-v["K"]))*(e^-(K*t)-e^-(k_a*t))`',
    //prettier-ignore
    equationTemplate: ``,
    multiple_dose: true,
    axis: ["time", "concentration"],
  },
];
